version: 1.0.{build}
build: off
test_script:
- cmd: >-
    choco install strawberryperl -version 5.20.1.1 --allow-empty-checksums -y

    SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%

    cpanm -nq POE Class::MethodMaker

    prove -lvr